### ISSUE TITLE
Alphabet order, search, API name

### ISSUE THREAD

**Issue by elenalazarus** [Patlatus/BofPerMan#1] opened 2019-06-25 08:58 UTC
When I was trying to use this package, I spent too much time looking for needed objects and fields because there is no alphabet order. Besides, I think that it would be useful to add some search field above the window with suggested objects/fields to make package usage easier. In addition, I think that it will be much more easier for developers if they look for objects/field by their API names, not Labels.

**Comment by Patlatus** [comment] 2019-06-25 09:29
Thanks for your feedback

**Comment by Patlatus** [comment] 2019-07-01 19:30
Alphabetic order was implemented; search was implemeted.
For displaying API names instead of labels I don't think to implement this right now, by design I want to display labels. Maybe I implement some option to select if user wants to see API name or label, but default value will always be label.

**Comment by Patlatus** [comment] 2021-10-01 08:03
Going to implement this in the next release using feature parameter

**Comment by Patlatus** [comment] 2021-11-23 17:54
The new package version is available on AppExchange. To upgrade to the new version, uninstall of the previous 1GMP version is required. The enhancement to include feature parameter flag for this ticket was included and released in that version.

**Closed as completed by Patlatus** 2021-11-23 17:54 UTC
Labels: 2GMP, Feature Parameter
