### ISSUE TITLE
Apex CPU Limit Exceeded - Bulk Field Permission Manager

### ISSUE THREAD

**Issue by Bobbygllh** [Patlatus/BofPerMan#6] opened 2021-10-15 11:58 UTC
Hi, 
Awesome tool and thanks for building. I am receiving the following error message on the Bulk Field Permission Manager tab

<img width="1167" alt="Screen Shot 2021-10-15 at 7 52 45 AM" src="https://user-images.githubusercontent.com/30133002/137482718-35db8eec-0895-4e0b-b637-8cea44c53ead.png">

I don't receive an error on the Bulk Object Permission Manager tab. The org I am using the managed package in doesn't have many objects or fields (relatively to other orgs ive worked in), 84 custom objects total including custom settings. Happy to help looking at any code.

**Comment by Patlatus** [comment] 2021-10-15 12:16
This sounds interesting, I used to received Apex CPU Time limit on save but not yet on retrieve. It might depend on the number of fields or on the org configuration. I am working now on 2GMP version of my package with new features.

Could you please install the new 2GMP version 04t09000000Rwh6AAC and grant me login access for the new package version on the affected org?

**Comment by Patlatus** [comment] 2021-10-15 15:55
I think this might happen because I try to build a map containing all the fields definitions at once, it might be better to fetch the definitions for given object on object selection.

Still, it would be helpful to get feedback if the issue reproduces on the 2GMP version of the package and get org configuration to understand how to reproduce this issue

**Comment by Bobbygllh** [comment] 2021-10-16 02:06
I installed the 2GMP package same issue. I am consulting on the org and dont have permission to give access but like i said this org only has 84 objects, I think loading the fields on object selection would be a lot more performant and avoid this eror

**Comment by Patlatus** [comment] 2021-10-16 13:36
I need to replicate the error so that later I could confirm it is resolved. Do you have admin access to retrieve all installed packages and objects with all fields using either this tool https://test-site.secure.force.com/ or any another tool so that I could deploy those to some scratch org and reproduce the issue?

**Comment by Patlatus** [comment] 2021-10-16 13:39
I mean even if I change the implementation to load the fields on object selection, this might still hit CPU time limit if user selects all the objects and I will not know if the fix works unless I could test this with environment where the error occurs

**Comment by Patlatus** [comment] 2021-10-18 20:56
@Bobbygllh I have performed some load testing over weekends. This is interesting that in unpackaged version almost 40000 fields can be processed without any CPU Time Limit error, but in the packaged version, CPU Time Error may occur at 800-1000 fields. Anyway when more than 700 fields are selected, the Lightning Experience UI starts to hang, so looks like it make sense not to select too many fields at once. 

Anyway I have created some trial version of the package which includes potential workaround for this issue. Would you like to beta test this version?

The pid is 04t1n000002SbyWAAS

**Comment by Patlatus** [comment] 2021-11-23 17:53
The new package version is available on AppExchange. To upgrade to the new version, uninstall of the previous 1GMP version is required. The enhancement for this ticket was included and released in that version.

**Closed as completed by Patlatus** 2021-11-23 17:53 UTC
Labels: 2GMP
